### ISSUE TITLE
notebook cna not run 

### ISSUE THREAD

**Issue by kehuaWangfff** [pjankiewicz/mercari-solution#1]
in mercari-solution/notebooks/tf_sparse.ipynb
from mercari import tf_sparse   
tf_sparse.load_data(small=small)   

tf_sparse not have load_data function

**Comment by lopuhin** [comment]
@kehuaWangfff indeed, the notebooks are not fully up to date, sorry about that. Please refer to https://github.com/pjankiewicz/mercari-solution/blob/master/mercari/main_tf.py instead, this is the one used to make a submission and it should work.
